// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateTrade(arg1) {
  return window['go']['main']['App']['CreateTrade'](arg1);
}

export function DeleteTrade(arg1) {
  return window['go']['main']['App']['DeleteTrade'](arg1);
}

export function GetActiveTradesByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetActiveTradesByDateRange'](arg1, arg2);
}

export function GetLatestMarketRating() {
  return window['go']['main']['App']['GetLatestMarketRating']();
}

export function GetSectorNames() {
  return window['go']['main']['App']['GetSectorNames']();
}

export function GetStrategyTypes() {
  return window['go']['main']['App']['GetStrategyTypes']();
}

export function GetTradeByID(arg1) {
  return window['go']['main']['App']['GetTradeByID'](arg1);
}

export function GetTrades(arg1, arg2) {
  return window['go']['main']['App']['GetTrades'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveMarketRating(arg1) {
  return window['go']['main']['App']['SaveMarketRating'](arg1);
}

export function UpdateMarketRating(arg1, arg2) {
  return window['go']['main']['App']['UpdateMarketRating'](arg1, arg2);
}

export function UpdateTrade(arg1, arg2) {
  return window['go']['main']['App']['UpdateTrade'](arg1, arg2);
}

export function UpdateTradeStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTradeStatus'](arg1, arg2);
}
