// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';

export function Close():Promise<void>;

export function CreateTrade(arg1:models.TradeRequest):Promise<models.OptionsTrade>;

export function DeleteTrade(arg1:number):Promise<void>;

export function GetActiveTradesByDateRange(arg1:time.Time,arg2:time.Time):Promise<Array<models.OptionsTrade>>;

export function GetLatestMarketRating():Promise<models.MarketRating>;

export function GetSectorNames():Promise<Array<string>>;

export function GetStrategyTypes():Promise<Array<models.StrategyType>>;

export function GetTradeByID(arg1:number):Promise<models.OptionsTrade>;

export function GetTrades(arg1:time.Time,arg2:time.Time):Promise<Array<models.OptionsTrade>>;

export function Greet(arg1:string):Promise<string>;

export function SaveMarketRating(arg1:models.MarketRatingRequest):Promise<models.MarketRating>;

export function UpdateMarketRating(arg1:number,arg2:models.MarketRatingRequest):Promise<models.MarketRating>;

export function UpdateTrade(arg1:number,arg2:models.TradeRequest):Promise<models.OptionsTrade>;

export function UpdateTradeStatus(arg1:number,arg2:string):Promise<models.OptionsTrade>;
